### ISSUE TITLE
Same Images Loaded using virtualScroll

### ISSUE THREAD

**Issue by tabirkeland** [zyramedia/ionic-image-loader#18]
When using with `virtualScroll` I am seeing the same images repeated as I scroll.

For example:
```html
  <ion-list [virtualScroll]="speakers" [approxItemHeight]="'70px'">
    <ion-item *virtualItem="let speaker" (click)="goToSpeakerDetail(speaker)">
      <ion-avatar item-left>
        <img-loader [src]="speaker.headshot" useImg [spinner]="false"></img-loader>
      </ion-avatar>
      <h2>{{ speaker.name }}</h2>
      <p>{{ speaker.title }}</p>
    </ion-item>
  </ion-list>
```

**Comment by ihadeed** [comment]
Thanks for reporting this bug @tabirkeland.

I will look into it right now.

**Comment by ihadeed** [comment]
@tabirkeland I'm unable to reproduce the issue you've described. 

See my code here: https://github.com/zyramedia/ionic-image-loader-example/tree/master/src/pages/virtual-scroll

**Comment by tabirkeland** [comment]
@ihadeed I will look into this and get back to you.

**Comment by tabirkeland** [comment]
@ihadeed I cloned your example repo and ran it on Android.  First, I was unable to build without first adding a `www` directory.  See (this)[https://github.com/driftyco/ionic-cli/issues/935}.  Second, I slightly modified your `virtual-scroll.html` template to do some comparison (with/without caching).  See below:

```html
<ion-header>

  <ion-navbar>
    <ion-title>Virtual Scroll</ion-title>
  </ion-navbar>

</ion-header>


<ion-content padding>
  <ion-list [virtualScroll]="images" [approxItemHeight]="'70px'">
    <button ion-item *virtualItem="let image" text-wrap>
      <ion-avatar item-left>
        <img-loader [src]="image" useImg [spinner]="false"></img-loader>
      </ion-avatar>
      <h2>Something here</h2>
      <p>More stuff here</p>
      <ion-avatar item-right>
        <img [src]="image">
      </ion-avatar>
    </button>
  </ion-list>
</ion-content>
```

Doing so and running on Android,  the two images do not match.

**Comment by ihadeed** [comment]
@tabirkeland sorry for the late response.

You're seeing different images because lorempixel.com will return a different image every time you access the URL. Since `img-loader` uses a native thread to pull the images, it will get a different image than what the `img` element gets.

I just updated the example project to use static images instead of lorempixel images. You can see now that images are consistent across `img` and `img-loader`.

**Comment by tabirkeland** [comment]
Thanks @ihadeed.  I will look into this again and get back to you.

**Comment by tabirkeland** [comment]
@ihadeed I updated the `VirtualScrollPage` class to populate a larger array of images and I am still seeing the issue.  Please see below:

```typescript
export class VirtualScrollPage
{
  public images: string[] = [];

  private baseImages: string[] = [
    'https://images.pexels.com/photos/27986/pexels-photo-27986.jpg?h=350&auto=compress&cs=tinysrgb',
    'https://images.pexels.com/photos/115010/tulips-red-red-tulips-garden-115010.jpeg?h=350&auto=compress&cs=tinysrgb',
    'https://images.pexels.com/photos/206393/pexels-photo-206393.jpeg?h=350&auto=compress&cs=tinysrgb',
    'https://images.pexels.com/photos/316591/pexels-photo-316591.jpeg?h=350&auto=compress&cs=tinysrgb',
    'https://images.pexels.com/photos/274060/pexels-photo-274060.jpeg?h=350&auto=compress&cs=tinysrgb',
    'https://images.pexels.com/photos/126345/pexels-photo-126345.jpeg?h=350&auto=compress&cs=tinysrgb',
    'https://images.pexels.com/photos/52977/coffee-coffee-maker-restaurant-cafe-52977.jpeg?h=350&auto=compress&cs=tinysrgb'
  ];

  public constructor()
  {
     for (var i = 0; i <= 25; i++) {
       this.baseImages.forEach((image) => {
         this.images.push(image + '?v=' + i);
       });
     }
  }
}
```

**Comment by ihadeed** [comment]
@tabirkeland Yup I can confirm this is a bug now. I will investigate and fix it soon.

**Comment by ihadeed** [comment]
Ok I figured it out. Turns out I fixed it in my last commit without knowing. Please update to `ionic-image-loader@1.6.0`

---

Explanation:

VirtualScroll doesn't remove and  re-add the elements inside `ion-item`. It only replaces the variables that need to be replaced. So the `img-loader` component doesn't get replaced, only it's `src` attribute value gets changed. 

Just until I pushed the last commit, this module didn't handle `src` changes. It kept the image set to the initial image that was passed to it. So what was going on here is that you only see the first set of images that were loaded, they get repeated and distributed randomly because of the way Virtual Scroll works.

**Comment by tabirkeland** [comment]
Great, thank you!

**Comment by elvisgraho** [comment]
Having the same issue right now with 2000 items in ion-virtual-scroll
