### ISSUE TITLE
ClearCache logic 

### ISSUE THREAD

**Issue by MarinoRaul** [zyramedia/ionic-image-loader#23]
Hello! I would want to know how can I manage when the user image is cached and for example his upload a new version of his image. I still saw the cached image of my user contact !
Does any internal logic of 304 response (resource not modified) and download the image when detected that this URL has changed?

Thanks a lot

**Comment by ihadeed** [comment]
The logic of this module is based on the URL provided. It converts the URL to a unique file name and checks if it exists in the file system. If the file doesn't exist, it will go ahead and download it. 

The best thing to do here is to modify your back end and instead of calling `https://myserver.com/user/profile-pic` to return the image, you return a full URL to where the image is saved (e.g: AWS S3). This way, when the user changes their image, the URL will change and then it will change in the app too.

Alternatively, you can add `noCache` attribute to the `img-loader` element. This will disable the caching for that instance.

**Comment by MarinoRaul** [comment]
Thanks for your response!

Any idea about this error???

{code: 3, source: "https://firebasestorage.googleapis.com/v0/b/…=media&token=b64e87e5-d9d7-469c-90b5-5a80c61d97c0", target: 
file:///data/data/com.ionicframework.testdev/cache/image-loader-cache/1382530553", http_status: null, body: null…}
body: null
code: 3
exception: "com.android.org.bouncycastle.jce.exception.ExtCertPathValidatorException: Could not validate certificate: Certificate not valid until Wed Feb 01 10:31:36 GMT-03:00 2017 (compared to Wed Aug 10 09:40:59 GMT-03:00 2016)"
http_status: null
source: "https://firebasestorage.googleapis.com/v0/b/test.appspot.com/o/user%2F3%2Favatar.jpg?alt=media&token=b64e87e5-d9d7-469c-90b5-5a80c61d97c0"
target: "file:///data/data/com.ionicframework.testdev/cache/image-loader-cache/1382530553
}

**Comment by MarinoRaul** [comment]
file:///assets/img/splash.png Failed to load resource: net::ERR_FILE_NOT_FOUND

**Comment by ihadeed** [comment]
Just published `1.7.1` that fixes the firebase issue.
