### ISSUE TITLE
Failback Image Issues

### ISSUE THREAD

**Issue by Craytor** [zyramedia/ionic-image-loader#29]
I'm trying to implement a fall back image implementation of ionic-image-loader.

I have noticed one small glitch with the loading icon as show in this short screen cap: http://shots.tjyouschak.me/vcHpFt.

More specifically the loading ion is too big and messes up the layout (when it is loading):
![image](https://cloud.githubusercontent.com/assets/3680866/24160567/9a59a4ce-0e38-11e7-9c50-59f558fc0686.png)
![image](https://cloud.githubusercontent.com/assets/3680866/24160586/a6c72966-0e38-11e7-9e0b-a0c018aca3d9.png)

**Comment by ihadeed** [comment]
Looks like when the page refreshes, the list is being re-created and therefore the `img-loader` component is being re-created as well. 

When the component first initializes, it will attempt to get the image you specified. If it fails to find it, then it will display the fallback image. 

I suggest that, when refreshing the page, you shouldn't replace the list items unless they have changed. This way you save the browser/webview some work. 

--

As for the spinner, I will be experimenting soon with integrating the Ionic Framework spinner instead of using my custom one. I will try to add an option for spinner size, or make it reactive/responsive to its parent container.

**Comment by ihadeed** [comment]
FYI: just published `ionic-image-loader@2.0.2` that uses Ionic Framework's spinner and Ionic Native v3.
